# Generated by Django 5.2 on 2025-04-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_api', '0001_initial'),
    ]

    operations = [
    ]
